/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as FinancialProfessionalsRouteImport } from './routes/financial-professionals'
import { Route as FaithBasedLeadersRouteImport } from './routes/faith-based-leaders'
import { Route as ConferenceRouteImport } from './routes/conference'
import { Route as ChurchCommunityRouteImport } from './routes/church-community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialProfessionalsRoute = FinancialProfessionalsRouteImport.update({
  id: '/financial-professionals',
  path: '/financial-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const FaithBasedLeadersRoute = FaithBasedLeadersRouteImport.update({
  id: '/faith-based-leaders',
  path: '/faith-based-leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceRoute = ConferenceRouteImport.update({
  id: '/conference',
  path: '/conference',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchCommunityRoute = ChurchCommunityRouteImport.update({
  id: '/church-community',
  path: '/church-community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/church-community': typeof ChurchCommunityRoute
  '/conference': typeof ConferenceRoute
  '/faith-based-leaders': typeof FaithBasedLeadersRoute
  '/financial-professionals': typeof FinancialProfessionalsRoute
  '/groups': typeof GroupsRoute
  '/learn': typeof LearnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/church-community': typeof ChurchCommunityRoute
  '/conference': typeof ConferenceRoute
  '/faith-based-leaders': typeof FaithBasedLeadersRoute
  '/financial-professionals': typeof FinancialProfessionalsRoute
  '/groups': typeof GroupsRoute
  '/learn': typeof LearnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/church-community': typeof ChurchCommunityRoute
  '/conference': typeof ConferenceRoute
  '/faith-based-leaders': typeof FaithBasedLeadersRoute
  '/financial-professionals': typeof FinancialProfessionalsRoute
  '/groups': typeof GroupsRoute
  '/learn': typeof LearnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/church-community'
    | '/conference'
    | '/faith-based-leaders'
    | '/financial-professionals'
    | '/groups'
    | '/learn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/church-community'
    | '/conference'
    | '/faith-based-leaders'
    | '/financial-professionals'
    | '/groups'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/church-community'
    | '/conference'
    | '/faith-based-leaders'
    | '/financial-professionals'
    | '/groups'
    | '/learn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChurchCommunityRoute: typeof ChurchCommunityRoute
  ConferenceRoute: typeof ConferenceRoute
  FaithBasedLeadersRoute: typeof FaithBasedLeadersRoute
  FinancialProfessionalsRoute: typeof FinancialProfessionalsRoute
  GroupsRoute: typeof GroupsRoute
  LearnRoute: typeof LearnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-professionals': {
      id: '/financial-professionals'
      path: '/financial-professionals'
      fullPath: '/financial-professionals'
      preLoaderRoute: typeof FinancialProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faith-based-leaders': {
      id: '/faith-based-leaders'
      path: '/faith-based-leaders'
      fullPath: '/faith-based-leaders'
      preLoaderRoute: typeof FaithBasedLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference': {
      id: '/conference'
      path: '/conference'
      fullPath: '/conference'
      preLoaderRoute: typeof ConferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/church-community': {
      id: '/church-community'
      path: '/church-community'
      fullPath: '/church-community'
      preLoaderRoute: typeof ChurchCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChurchCommunityRoute: ChurchCommunityRoute,
  ConferenceRoute: ConferenceRoute,
  FaithBasedLeadersRoute: FaithBasedLeadersRoute,
  FinancialProfessionalsRoute: FinancialProfessionalsRoute,
  GroupsRoute: GroupsRoute,
  LearnRoute: LearnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
